# Generated by Django 5.0.1 on 2024-01-24 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0003_portfolio_datecreated"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="asset_name",
            field=models.CharField(default="asset", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="ticker",
            field=models.CharField(default="ticker", max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transaction",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="portfolio.asset",
            ),
        ),
    ]
