# Generated by Django 5.0.1 on 2024-03-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0004_transaction_asset_name_transaction_ticker_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="units",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
    ]
